[env:seeed_xiao_esp32c3]
platform = espressif32@^6.2.0
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

; 强制指定串口端口，防止其连接到 Mac 的蓝牙
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101

build_flags = 
    -D CONFIG_PM_ENABLE
    -D CONFIG_I2S_SUPPRESS_DEPRECATE_WARN=1
    ; 必须添加下面这两行，否则监视器会一直是空的
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1